# Generated by Django 4.0.2 on 2022-04-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_grade_payments_semester_remove_payments_roll_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='id',
        ),
        migrations.AlterField(
            model_name='payments',
            name='entry',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
