# Generated by Django 4.0.2 on 2022-04-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_payments_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payments',
            name='entry',
            field=models.CharField(max_length=12),
        ),
    ]
