# Generated by Django 4.0.2 on 2022-04-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_payments_id_alter_payments_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='entry',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
