# Generated by Django 4.0.2 on 2022-04-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_payments_id_alter_payments_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='payment_id',
            field=models.AutoField(default=123, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payments',
            name='entry',
            field=models.CharField(max_length=12),
        ),
    ]
