# Generated by Django 4.0.2 on 2022-04-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_payments_payment_id_payments_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('entry', models.CharField(max_length=12)),
                ('semester', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
    ]
