# Generated by Django 4.0.2 on 2022-04-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_feespayments_delete_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feespayments',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
